### ISSUE TITLE
[FR] Add option to allow slaves free will.

### ISSUE THREAD

**Issue by lizelive** [paul-freeman/rimworld-freewill#1]
RP reason: the colony is telling them what to do.

**Comment by paul-freeman** [comment]
Thanks for taking the time to request this change. Slaves don't have free will by design. If you want them to do their own thing, you'll need to free them.
https://github.com/paul-freeman/rimworld-freewill/blob/8a3534af9f0ccfe8f8935a8008f48edaaa59a8dd/description.txt#L54
